package db

import (
	"database/sql"
	"errors"
	"fmt"
	"os"

	tgbotapi "github.com/go-telegram-bot-api/telegram-bot-api/v5"
	"github.com/gofrs/uuid"
)

type DevSesh struct {
	ChatId int64
	User   User
	State  DevState
}

type DevState string

const (
	StateWaitingForCleaningCSV DevState = "waiting_for_cleaning_csv"
	StateDormantDev            DevState = "dormant_dev"
)

var ErrNotSuperAdmin = errors.New("not a super admin")

// user should not be empty
func (u *User) SendRequestToSuperAdmins(exec DBExecutor, bot *tgbotapi.BotAPI) error {
	var chatIds []int64
	rows, err := exec.Query("SELECT chat_id FROM users where is_super_admin=1")
	if err != nil {
		return fmt.Errorf("ERR: getting superadmin's chatids: %v\n", err)
	}
	defer rows.Close()

	i := 0
	var temp int64
	for rows.Next() {
		i++
		err = rows.Scan(&temp)
		if err != nil {
			return fmt.Errorf("ERR: scanning rows (i: %d): %v\n", i, err)
		}
		chatIds = append(chatIds, temp)
	}

	if rows.Err() != nil {
		return rows.Err()
	}

	var role Role

	if u.DriverId != uuid.Nil {
		role = RoleDriver
	} else if u.ManagerId != uuid.Nil {
		role = RoleManager
	}

	if role == "" {
		return fmt.Errorf("ERR: User does not have driver or manager id: %v\n", u)
	}

	bot.Send(tgbotapi.NewMessage(u.ChatId, "Дані відправлені Адміністратору для перевірки..."))
	for _, v := range chatIds {

		request := tgbotapi.NewMessage(v,
			fmt.Sprintf(
				"Новий запрос на реєстрацію\n\nКористувач з імʼям <b>%s</b> (@%s)\nРоль: %s",
				u.Name, u.TgTag, role,
			),
		)
		request.ReplyMarkup = tgbotapi.NewInlineKeyboardMarkup(
			tgbotapi.NewInlineKeyboardRow(tgbotapi.NewInlineKeyboardButtonData("Підтвердити", fmt.Sprintf("sa:approve:%d", u.ChatId))),
			tgbotapi.NewInlineKeyboardRow(tgbotapi.NewInlineKeyboardButtonData("Відмовити", fmt.Sprintf("sa:decline:%d", u.ChatId))),
		)
		request.ParseMode = tgbotapi.ModeHTML

		bot.Send(request)
	}

	return nil
}

func (u *User) FindSuperAdmin(storage DBExecutor) error {
	isManager, err := u.IsManager(storage)
	if err != nil {
		return fmt.Errorf("ERR: checking if super admin or not: %v\n", err)
	}

	if !isManager {
		return fmt.Errorf("ERR: not even a manager")
	}

	row := storage.QueryRow("SELECT is_super_admin from users where id = ?", u.Id)
	if err = row.Scan(&u.IsSuperAdmin); err != nil {
		return err
	}

	if u.IsSuperAdmin {
		return nil
	}

	return ErrNotSuperAdmin
}

func GetDev(globalStorage *sql.DB, chat_id int64) (*DevSesh, error) {

	if os.Getenv("CURRENT_DEV_ID") == "" {
		return nil, fmt.Errorf("you gotta have a CURRENT_DEV_ID with your autogenerated uuid from the sqlite db to access this in .env")
	}

	devSesh := new(DevSesh)
	devSesh.User = User{}

	row := globalStorage.QueryRow("SELECT id, chat_id, name, manager_id, created_at, updated_at, is_super_admin, tg_tag FROM users WHERE id = ?", os.Getenv("CURRENT_DEV_ID"))
	err := row.Scan(
		&devSesh.User.Id,
		&devSesh.User.ChatId,
		&devSesh.User.Name,
		&devSesh.User.ManagerId,
		&devSesh.User.CreatedAt,
		&devSesh.User.UpdatedAt,
		&devSesh.User.IsSuperAdmin,
		&devSesh.User.TgTag,
	)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, fmt.Errorf("not a dev")
		}
		return nil, fmt.Errorf("ERR: scanning user: %w", err)
	}

	if chat_id > 0 {
		devSesh.ChatId = chat_id
	} else if devSesh.User.ChatId > 0 {
		devSesh.ChatId = devSesh.User.ChatId
	} else {
		return nil, fmt.Errorf("how do you not have a chat id? permission declined")
	}

	devSesh.State = StateDormantDev

	return devSesh, nil

}
